---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: kube-system
data:
  traefik.toml: |
    # traefik.toml
    defaultEntryPoints = ["http","https"]
    InsecureSkipVerify = true
    useXForwardedFor = true
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      #[entryPoints.http.redirect]
      #entryPoint = "https"
      # Do not verify backend certificates (use https backends)
      [entryPoints.https]
      address = ":443"
      [entryPoints.https.tls]